# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Movie.create(name: "Dia de la Independencia", synopsis: "Una flota de naves espaciales llega a la Tierra en la víspera del 4 de julio, el Día de la Independencia en Estados Unidos. La sorpresa inicial se convierte en terror cuando las naves empiezan a atacar el planeta lanzando rayos destructivos contra algunas de las mayores ciudades del mundo. Los únicos que pueden salvar la Tierra son una serie de supervivientes que planean un ataque masivo contra los alienígenas antes de que sea demasiado tarde.
", director: "Roland Emmerich")
Movie.create(name: "Titanic", synopsis: "Jack es un joven artista que gana un pasaje para viajar a América en el Titanic, el transatlántico más grande y seguro jamás construido. A bordo del buque conoce a Rose, una chica de clase alta que viaja con su madre y su prometido Cal, un millonario engreído a quien solo interesa el prestigio de la familia de su prometida. Jack y Rose se enamoran a pesar de las trabas que ponen la madre de ella y Cal en su relación. Mientras, el lujoso transatlántico se acerca a un inmenso iceberg.", director: "James Cameron")
Movie.create(name: "Avatar", synopsis: "En un exuberante planeta llamado Pandora viven los Na'vi, seres que aparentan ser primitivos pero que en realidad son muy evolucionados. Debido a que el ambiente de Pandora es venenoso, los híbridos humanos/Na'vi, llamados Avatares, están relacionados con las mentes humanas, lo que les permite moverse libremente por Pandora. Jake Sully, un exinfante de marina paralítico se transforma a través de un Avatar, y se enamora de una mujer Na'vi.", director: "James Cameron")
Movie.create(name: "El Juego de Ender", synopsis: "Un joven talentoso exhibe un talento inusual que hace que sea elegido para un entrenamiento militar avanzado para encabezar a las fuerzas de la Tierra en una guerra intensa contra los Formics, unos invasores extraterrestres.", director: "Gavin Hood")
Movie.create(name: "Moulin Rouge", synopsis: "Satine, la estrella más rutilante del Moulin Rouge, encandila a toda la ciudad con sus bailes llenos de sensualidad. Atrapada entre el amor de dos hombres, un joven escritor y un duque, lucha por hacer realidad su sueño de ser actriz.", director: "Baz Luhrmann")

Series.create(name: "Star Trek", synopsis: "El joven James T. Kirk, Spock y el resto de la tripulación del Enterprise se embarcan en un curso de colisión con un romulano vengativo.", director: "J. J. Abrams")
Series.create(name: "Lost", synopsis: "Lost es una serie dramática que se centra en las vivencias de los 'supervivientes' de un accidente aéreo en una isla llena de misterios. Por lo general, cada episodio narra una historia principal que tiene lugar en la isla, intercalada con varios segmentos de una historia secundaria.", director: "J. J. Abrams")
Series.create(name: "The Walking Dead", synopsis: "La historia de The Walking Dead nos traslada a un escenario post-pandémico en el que un virus ha acabado con la práctica totalidad de la población mundial convirtiéndolos en zombis. Seremos testigo de la lucha de un grupo de supervivientes por mantenerse a salvo en este entorno infestado de zombis o, como ellos prefieren llamarlos, caminantes.", director: "Frank Árpád Darabont")
Series.create(name: "Perdidos en el Espacio", synopsis: "El profesor John Robinson se embarca junto a su familia en la nave Júpiter II para colonizar un planeta aislado en el espacio. Pero en la nave también navega el Dr. Smith, enviado por fuerzas enemigas para sabotear la misión, que provocará un incidente a partir del cual la nave deambulará sin rumbo fijo por las galaxias.", director: "Stephen Hopkins")
Series.create(name: "No Ordinary Family", synopsis: "Después de 16 años de matrimonio, la relación entre Jim y Stephanie Powell no tiene la chispa que tenia al principio, y su vida familia consiste solamente en encontrar el equilibrio entre el trabajo y sus dos hijos.", director: "Greg Berlanti")

DocumentaryFilm.create(name: "This is It", synopsis: "Antes de su inesperada muerte, Michael Jackson estaba en medio de la preparación de una serie de conciertos con todas las entradas vendidas que debería haberse realizado en el verano del 2009 en Londres. Imágenes detrás de las cámaras, filmadas entre marzo y junio del 2009, muestran detalladamente a la popular superestrella, mientras se desarrolla y ensaya para su gira 'This Is It'.", director: "Kenny Ortega")
DocumentaryFilm.create(name: "El dilema de las redes sociales", synopsis: "Expertos en tecnología de Silicon Valley hacen sonar la alarma sobre el peligroso impacto de las redes sociales, que Big Tech utiliza en un intento de manipular e influir.", director: "Jeff Orlowski")
DocumentaryFilm.create(name: "La Reina Cleopatra", synopsis: "La lucha de Cleopatra, última faraona de Egipto, por proteger el trono, su legado y a su familia de la ambición del Imperio romano.", director: "Jada Pinkett Smith")
DocumentaryFilm.create(name: "Stan Lee", synopsis: "Stan Lee y su trayectoria hasta convertirse en una de las personas más influyentes del mundo de los cómics y la cultura pop.", director: "David Gelb")
DocumentaryFilm.create(name: "Free to Play", synopsis: "Tres jugadores profesionales de videojuegos superan la adversidad, las presiones familiares y las realidades de la vida para competir por un millón de dólares.", director: "Valve Company")
